---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/robot_control"
    schedule:
      interval: "daily"
      # Ensure we dont try to bump exp past 49.0 (ignore major?)
    ignore:
      - dependency-name: "expo"
        update-types: ["version-update:semver-major"]
