---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/test"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
